[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://pothole-detection-yolo.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
